### PR TITLE
New WebRTC Hosted Page examples for WSE 4.8.5 release

### PR DESCRIPTION
**Pull request by razorborg**

### CODE REVIEW

**Comment by nielsenaa** [comment]
Up ! Pretty please !  :)
am on a 4.8.0 dev edition (btw 4.8.0 is an official release) , and the dev-view-publish boilerplate is so much sexier (uses rtc adapter, is way more cross-browser ready, and includes inputs and frameSize handling ;) 

Surely, i'd rather package and deliver this to my actual customer next week, than the tweaked 4.7.7 examples next month ;) 
So please yes !

**Comment by bestlane** [comment]
+1

**Comment by akeller** [comment]
@nielsenaa This is being staged for release.

**Comment by nielsenaa** [comment]
@akeller Great ! thank you ! :)

**Pull request merged**
